name: Backup Lpx Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点运行

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests

      - name: Download Lpx files
        env:
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        run: python download_lpx.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add *.lpx
          git commit -m "Update Lpx files" || echo "No changes"
          git push
